name: 'Github Maintenance Action'
description: 'Executing maintenance tasks on Github.'
author: 'Viascom Ltd liab. Co | Nikola Stanković <nikola.stankovic@viascom.email>'

inputs:
  github_token:
    description: 'Authentication token'
    required: true
    default: ${{ github.token }}

  github_base_url:
    description: 'Base API URL'
    required: false
    default: "https://api.github.com"

  repository:
    description: 'Name of the repository.'
    required: true
    default: ${{ github.repository }}

  retention_days:
    description: 'Retention time in days of runs to keep.'
    required: true
    default: 31

  delete_logs:
    description: 'Deletes only the logs of the workflow runs.'
    required: false
    default: false

  delete_artifacts:
    description: 'Deletes only the artifacts of the workflow runs.'
    required: false
    default: false

  dry_run:
    description: 'Logs simulated changes, no actions are performed!'
    required: false
    default: false

  debug:
    description: 'When debug is enabled more logs will be printed.'
    required: false
    default: false

runs:
  using: 'docker'
  image: 'docker://viascom/github-maintenance-action:latest'
  args:
    - /etc/run_application.sh
    - ${{ inputs.github_token }}
    - ${{ inputs.github_base_url }}
    - ${{ inputs.repository }}
    - ${{ inputs.retention_days }}
    - ${{ inputs.delete_logs }}
    - ${{ inputs.delete_artifacts }}
    - ${{ inputs.dry_run }}
    - ${{ inputs.debug }}

branding:
  icon: 'settings' # https://feathericons.com/ - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#brandingicon
  color: 'purple' # The background color of the badge. Can be one of: white, yellow, blue, green, orange, red, purple, or gray-dark.
