name: "GitHub Maintenance Action"
description: "Executing maintenance tasks on GitHub — delete old workflow runs, artifacts, and logs."
author: "Viascom Ltd liab. Co | Nikola Stanković <nikola.stankovic@viascom.email>"

inputs:
  github_token:
    description: "GitHub authentication token (usually pass: secrets.GITHUB_TOKEN)."
    required: true

  repository:
    description: "Repository name in format 'owner/repo'."
    required: true
    default: ${{ github.repository }}

  retention_days:
    description: "Retention time in days for workflow runs to keep."
    required: true
    default: 31

  keep_minimum_runs:
    description: "Minimum number of latest workflow runs to always keep."
    required: true
    default: 5

  # OPTIONAL INPUTS
  github_base_url:
    description: "GitHub API base URL. Defaults to public GitHub API."
    required: false
    default: "https://api.github.com"

  delete_logs:
    description: "If true, deletes only the logs of workflow runs. If false and delete_artifacts is also false, the entire workflow run will be deleted."
    required: false
    default: false

  delete_artifacts:
    description: "If true, deletes only the artifacts of workflow runs. If false and delete_logs is also false, the entire workflow run will be deleted."
    required: false
    default: false

  actors:
    description: "Comma-separated list of actors whose workflow runs to delete. If empty, no actor filtering is applied."
    required: false
    default: ""

  branches:
    description: "Comma-separated list of branches whose workflow runs to delete. If empty, no branch filtering is applied."
    required: false
    default: ""

  events:
    description: "Comma-separated list of workflow run events to delete. If empty, no event filtering is applied."
    required: false
    default: ""

  statuses:
    description: "Comma-separated list of workflow run statuses to delete. If empty, no status filtering is applied."
    required: false
    default: ""

  keep_pull_requests:
    description: "If true, pull request workflow runs will always be kept."
    required: false
    default: false

  dry_run:
    description: "If true, logs simulated changes but does not perform any deletions (artifacts, logs, or runs)."
    required: false
    default: false

  debug:
    description: "If true, enables debug logging."
    required: false
    default: false

runs:
  using: "docker"
  image: "docker://ghcr.io/viascom/github-maintenance-action:latest"
  args:
    - /etc/run_application.sh
    - ${{ inputs.github_token }}
    - ${{ inputs.github_base_url }}
    - ${{ inputs.repository }}
    - ${{ inputs.retention_days }}
    - ${{ inputs.keep_minimum_runs }}
    - ${{ inputs.delete_logs }}
    - ${{ inputs.delete_artifacts }}
    - ${{ inputs.actors }}
    - ${{ inputs.branches }}
    - ${{ inputs.events }}
    - ${{ inputs.statuses }}
    - ${{ inputs.keep_pull_requests }}
    - ${{ inputs.dry_run }}
    - ${{ inputs.debug }}

branding:
  icon: "settings" # https://feathericons.com/ - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#brandingicon
  color: "purple" # The background color of the badge. Can be one of: white, yellow, blue, green, orange, red, purple, or gray-dark.
