name: Build and Push

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.sql'
      - '.github/**'
      - 'http-requests/**'
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      publish:
        description: Publish images to Docker Hub?
        type: boolean
        required: true
        default: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: |
          sudo timedatectl set-timezone Europe/Zurich
          timedatectl

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          java-package: jdk
          architecture: x64
          cache: 'gradle'
          check-latest: false

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Change Gradle Wrapper permissions
        run: chmod +x ./gradlew

      - name: Build darkstim-bot (build-only)
        if: "${{ github.event.inputs.publish == 'false' || github.event.inputs.publish == '' }}"
        run: ./gradlew clean build docker --warn --stacktrace

      - name: Build and push darkstim-bot
        if: "${{ github.event.inputs.publish == 'true' }}"
        run: ./gradlew clean build dockerPush --warn --stacktrace --scan

      - name: Upload darkstim-bot artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: github-maintenance-action-build-libs
          path: github-maintenance-action/build/libs
          retention-days: 7
